### ISSUE TITLE
.ofocus file format docs?

### ISSUE THREAD

**Issue by ariporad** [psidnell/ofexport2#12]
Hi!

I was wondering where you guys found documentation on the `.ofocus` file format?

Thanks!

**Comment by psidnell** [comment]
It actually doesn't use the .ofocus files, it reads the database. I did originally think about using the ofocus files, but never found any documentation, I also wasn't sure if the data was spread across several files. The DB seemed easier.

**Comment by ariporad** [comment]
@psidnell: Ok, Thanks!
