### ISSUE TITLE
Add DB location for OmniFocus 2 purchased from Mac App Store

### ISSUE THREAD

**Issue by gaomd** [psidnell/ofexport2#5]
The DB location for OmniFocus 2 purchased from Mac App Store is:

    ${HOME}/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2

**Comment by psidnell** [comment]
Thanks - I'll add that to the list

**Comment by psidnell** [comment]
Fixed in V1.0.19.
